### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by hmueller01** [EdLeafe/pyexif#6]
I get a `RuntimeError: Warning: [minor] Fixed incorrect URI for xmlns:MicrosoftPhoto` on some of my photos. `_runproc` raises on all "errors". Would it be possible to ignore all "Warnings" (as it is only a warning and no error)?

**Comment by EdLeafe** [comment]
Is this coming from https://github.com/EdLeafe/pyexif/blob/master/pyexif/__init__.py#L49 ?

If so, I suppose it could be wrapped to catch that message and ignore it.

**Comment by hmueller01** [comment]
Thanks, that is what I did in the mean time. I thought there would be a better way (e.g. by optionally filtering these warning in that function).
