### ISSUE TITLE
setTag fails when getTag show that the tag exists

### ISSUE THREAD

**Issue by OneGneissGuy** [EdLeafe/pyexif#7]
Expect the ability to overwrite a tag. However, when I try to write to the tag, `exiftool` returns the tag isn't available.

```
pyexif_img = pyexif.ExifEditor(photo=img_fname, save_backup=True)
pyexif_img.getTag('RigName')

Out[47]: 'SlantRange-3P'

In [49]: pyexif_img.setTag('RigName', 'Altum')
Traceback (most recent call last):

  File "<ipython-input-49-6d449a342efc>", line 1, in <module>
    pyexif_img.setTag('RigName', 'Altum')

  File "Python Scripts\convert_sr\pyexif\pyexif\__init__.py", line 265, in setTag
    out = _runproc(cmd, self.photo)

  File "Python Scripts\convert_sr\pyexif\pyexif\__init__.py", line 50, in _runproc
    raise RuntimeError(err)

RuntimeError: b"Warning: Tag 'RigName' is not defined\r\nNothing to do.\r\n"
```

**Comment by OneGneissGuy** [comment]
This is likely an issue with `Exiftool` rather than `pyexif`, I was able to replicate pyexif codes behavior at the terminal

**Comment by EdLeafe** [comment]
I'm a little confused how the square brackets got added to the command. The error states

`  Invalid tag name '['RigName']'`

...and it should just be `'RigName'`

**Comment by OneGneissGuy** [comment]
I was debugging and mixed up my outputs. Issue updated.

**Comment by EdLeafe** [comment]
So it sounds like this is an issue with exiftool. Is that your impression? If so, we can close this issue. If not, maybe you could provide a generic example that displays the error.
